### ISSUE TITLE
Incorrect Pixel localization

### ISSUE THREAD

**Issue by BGERI95** [glami/glami-feed-generator-pixel-for-woocommerce#1]
The localization of the js code should be set dynamically based on the setting. 
In [Line 42 of class-glami-feed-generator-pixel-for-woocommerce-public.php](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/blob/4e487f43b5394ce7af596b17ca62763905a529b6/public/class-glami-feed-generator-pixel-for-woocommerce-public.php#L42) the galmi_pixel_key is set correctly, while the localization parameter is a constant value 'gr'. This should also be replaced with the variable from the WooCommerce backend.

`glami('create', '".$this->glami_settings['glami_pixel_key']."', 'gr');`

**Comment by seldimi** [comment]
The issue was patched in 1.0.2
