### ISSUE TITLE
Bug Report: Missing Category Administration After Installing and Activating the Glami App

### ISSUE THREAD

**Issue by tyfricko** [glami/glami-feed-generator-pixel-for-woocommerce#11]
**Summary:**
After installing and activating the Glami app, the category administration functionality has disappeared from the application's interface.

**Steps to Reproduce:**

1. Install the Glami app on a compatible platform.
2. Activate the Glami app as per the provided installation instructions.
3. Navigate to the section of the application related to category administration.
4. Observe that the category administration functionality is not visible or accessible.

**Expected Behavior:**
Upon installing and activating the Glami app, the category administration functionality should remain unaffected. Users should be able to access and manage categories as they did prior to installing the app.

**Actual Behavior:**
After the Glami app is installed and activated, the category administration section is missing from the application interface. Users are unable to manage categories, which is an essential part of the application's functionality.

**Additional Information:**

Platform: Wordpress - v6.3
Glami Plugin Version: 1.0.9
Other Installed Plugins/Extensions: WooCommerce - v8.0.2, Woodmart theme - v7.2.5, 
Screenshots: https://ibb.co/qDQTynb

Possible Workarounds: Deactivating the Glami plugin restores the category usability

**Notes:**

This issue severely impacts the usability of the application, as category administration is a crucial feature for organizing and managing content.
It's recommended to investigate the Glami app's code and compatibility with other plugins to isolate the cause of this issue.
Please address this bug as it hinders the smooth operation of the application's core functionality. If you need further details or assistance in replicating the issue, please feel free to contact me.

Thank you for your prompt attention to this matter.

Sincerely,
Matej Zlatič

**Comment by seldimi** [comment]
Hello
Glami pluign doesn't affect the product category screen, it just adds two fields on new/edit product category.
The white box shown on your screenshot, is not native from WordPress/WooCommerce, so that means your theme or a third party plugin adds content.

In order to help us investigate the issue, please enable wp_debug and check for any fatal errors while being on that page.

**Comment by tyfricko** [comment]
Thank you for the respone. I've enabled the wp-debug and this is the error log:

> Warning: simplexml_load_file(): [HIDE]/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/categories/glami.si.xml:1: parser error : Start tag expected, '<' not found in [HIDE]/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/admin/class-glami-feed-generator-pixel-for-woocommerce-admin.php on line 115

> Warning: simplexml_load_file(): This XML file does not appear to have any style information associated with it. in [HIDE]/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/admin/class-glami-feed-generator-pixel-for-woocommerce-admin.php on line 115

> Warning: simplexml_load_file(): ^ in [HIDE]/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/admin/class-glami-feed-generator-pixel-for-woocommerce-admin.php on line 115

> Notice: Trying to get property 'CATEGORY' of non-object in [HIDE]/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/admin/class-glami-feed-generator-pixel-for-woocommerce-admin.php on line 127

> Fatal error: Uncaught Error: Call to a member function count() on null in [HIDE]/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/admin/class-glami-feed-generator-pixel-for-woocommerce-admin.php:121 Stack trace: #0 [HIDE]/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/admin/class-glami-feed-generator-pixel-for-woocommerce-admin.php(127): printChildren(false, NULL, Array) #1 [HIDE]/wp-includes/class-wp-hook.php(310): Glami_Feed_Generator_Pixel_For_Woocommerce_Admin->glami_category_mapping_taxonomy_add_new_meta_field('product_cat') #2 [HIDE]/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array) #3 [HIDE]/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #4 [HIDE]/wp-admin/edit-tags.php(542): do_action('product_cat_add...', 'product_cat') #5 {main} thrown in [HIDE]/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/admin/class-glami-feed-generator-pixel-for-woocommerce-admin.php on line 121

**Comment by seldimi** [comment]
Hello
Can you check on the plugin version and if all files were consistent ?
The above message says that glami.si.xml is missing from the folder, though its not:
https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/tree/main/includes/categories

**Comment by seldimi** [comment]
Issue closed due to inactivity
