### ISSUE TITLE
Settings on Glami feed generator

### ISSUE THREAD

**Issue by dragoev10** [glami/glami-feed-generator-pixel-for-woocommerce#12]
Hello,

Where i can find settings on this plugin, so i can set up xml?
I looking everywhere in my control panel, but i can't find settings for this plugin!

Greetings

![glami plugin](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/145332441/4e5b2c06-85a4-4d71-b1f3-c2bbbe5c5f19)

**Comment by seldimi** [comment]
Hello
You can find Glami settings on WooCommerce > Settings > Integrations tab.

**Comment by lukasprelovsky** [comment]
It might be appropriate to add a link to the settings next to the deactivate url of the plugin. it is the wordpress standard in the world

example:

![scr](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/c7941a7e-d75b-4062-a855-0e4aad80ae21)

**Comment by lukasprelovsky** [comment]
https://mead.io/2022/06/08/add-a-link-to-your-plugin-from-the-wordpress-plugin-list/

**Comment by seldimi** [comment]
Will be added in the next release, later today.
