### ISSUE TITLE
We cant choose the attributes that will be used for manufacturer attribute in XML

### ISSUE THREAD

**Issue by augpaschal** [glami/glami-feed-generator-pixel-for-woocommerce#13]
In our online store, we use the xstore theme.

Regarding the manufacturer information, in our system, it is stored in a field called "brand" (product-tags), which we cannot select in the plugin settings (the available options are only attributes).

In corresponding export XML files (Bestprice, Skroutz), this field is available in their settings, as you can see below:

![skroutz-bestprice-xml](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/5956622/482995de-8f25-4dea-bb54-d077e212a190)

However, in the Glami plugin, this option is not provided.

![glami-xml](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/5956622/97b9241d-9ff6-49a2-9d41-45e481bd65a5)

**Comment by seldimi** [comment]
Hello.
Currently, GLAMI plugin only support WooCommerce attributes and not custom taxonomies on selection fields. We might implement it in near future.
Thank you

**Comment by lukasprelovsky** [comment]
I agree with this initiative, it would be appropriate to define the brand, for example, in text, and not depend on the use of properties :)
