### ISSUE TITLE
Mandatory parameters - DELIVERY_DATE - is not in the xml feed if the product is in stock 0 + Available on Backorders

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#14]
Hi,

If the product is "in stock", but has 0 units, and it is allowed:

Available on Backorders + notice

so the mandatory parameter is not displayed in the xml feed:

DELIVERY_DATE

which is mandatory for glami operation.

In glami settings admin.php?page=wc-settings&tab=integration&section=glami-feed-generator-pixel-for-woocommerce

I have set that products that are not in stock should also be displayed.

the DELIVERY_DATE (https://www.glami.sk/info/feed/#_feed-tag-delivery_date) parameter is not found in the xml

It would be appropriate to add that a fixed delivery value of e.g. 30 days should be set for the warehouse status Available on Backorders.

So it would be possible to add support that if the product is in stock, but has 0 pcs, or is available from the supplier, a value of e.g. 30 days delivery time is set, or it would be even better to add this option to the module settings, where the number would be defined days manually customized.

thanks for the reply :)

**Comment by lukasprelovsky** [comment]
simple product setup:

![Screenshot 2023-10-06 at 21-50-08 Edit product “Orange Oval Dog Tag from Divanoodle” ‹ arrogant-antelope-xvw5z instawp xyz — WordPress](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/fc5acf90-f4cd-4187-a7c1-70513f997858)

variable product setup:
![Screenshot 2023-10-06 at 21-51-50 Edit product “Soflyy T-Shirt” ‹ arrogant-antelope-xvw5z instawp xyz — WordPress](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/5f55eb46-87a7-4e4a-93ae-97c61f11a2a7)

Option: Manage stock, 0 stock pcs in stock, (Allow, but notify customer)

**Comment by lukasprelovsky** [comment]
I analyzed the problem more deeply and I came to the conclusion that the code will probably be outdated and unusable with the new woocommerce (I'm currently using 8.x)

/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/class-glami-feed-generator-pixel-for-woocommerce-engine.php
```

	if ($product->is_in_stock() && !$product->backorders_allowed()) {
			$delivery_date=0;
            $shopitem->appendChild($domtree->createElement('delivery_date',$delivery_date));
		} else {
			if ($product->backorders_allowed() && $product->get_stock_quantity() > 0) {
				$delivery_date=0;
                $shopitem->appendChild($domtree->createElement('delivery_date',$delivery_date));
			}
		}

```

this code will not work for backorders (get_stock_quantity) because getting the value doesn't work

after deleting `&& $product->get_stock_quantity() > 0` the code is working

**Comment by seldimi** [comment]
Will be fixed in the next release, later today.
