### ISSUE TITLE
Colour attribute is not displayed in the XML feed

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#15]
Hi,

I have filled in the Color attribute, but it is not displayed in the XML feed.

settings page:
![Colour](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/ee166271-db8d-4f70-a9d6-48fcb5344618)

attribute name and values
![attribute](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/0eec42c8-7b25-4c5a-998a-98eda7c4710d)

thanks for the reply

**Comment by seldimi** [comment]
Will be added in the next release, later today.
