### ISSUE TITLE
Glami TOP integration

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#16]
Hi,

are you not planning to add GLAMI TOP integration as well?

in the checkout, the code would look like this, for example

```
add_action('woocommerce_thankyou', 'glami_top_integration',120 );

function glami_top_integration($order_id){
$order = new WC_Order( $order_id );
echo "<!-- Start GLAMI TOP tracking--> <script>";
?>(function (f, a, s, h, i, o, n) {
f['GlamiOrderReview'] = i;
f[i] = f[i] || function () {(f[i].q = f[i].q || []).push(arguments);};
o = a.createElement(s), n = a.getElementsByTagName(s)[0];
o.async = 1; o.src = h; n.parentNode.insertBefore(o, n);
})(window,document,'script','//www.glami.sk/js/compiled/or.js', 'glami_or');

glami_or('addParameter', 'merchant_id','111111111111111111111111111', 'sk');
glami_or('addParameter', 'order_id', '<?php echo $order->get_order_number(); ?>');
glami_or('addParameter', 'email', '<?php echo $order->get_billing_email(); ?>');
glami_or('addParameter', 'language', 'sk');
glami_or('addParameter', 'items', [
  <?php
$keysX = array_keys($order->get_items());
$last_key = end($keysX);
foreach ( $order->get_items() as $key => $item ) :
	$product = $order->get_product_from_item($item);                    
?>
	{
		id: '<?php echo $item['product_id']; ?>',
		name: '<?php echo $item['name']; ?>'
	}
	
<?php 
if ($key != $last_key) {
        echo ', ';
    }
endforeach; ?>

]);

glami_or('create');
<?php
echo "</script> <!-- End of GLAMI TOP Tracking -->";
}
```

You would only have to program the following things into the module settings to add to the code:

Language code:
`language - glami_or('addParameter', 'language', 'sk'); `

Merchant ID:
`glami_or('addParameter', 'merchant_id','111111111111111111111111111', 'sk');`

Country script url
`})(window,document,'script','//www.glami.sk/js/compiled/or.js', 'glami_or'); `

I think it would help many people

Thanks

**Comment by seldimi** [comment]
Hello.
Can you share the documentation the describes that feature?

**Comment by lukasprelovsky** [comment]
Hi,

yes

this: https://www.glami.sk/info/reviews/implementation/
en: https://www.glami.eco/info/reviews/implementation/

**Comment by seldimi** [comment]
Thank you for you instant reply.
We will evaluate it and add it as a feature on a future release.

**Comment by lukasprelovsky** [comment]
Perfect, thx

**Comment by lukasprelovsky** [comment]
I fixed the code for 100% functionality, tested on 1 product and 2 or more products.

There was a problem in the flood code that it did not add a separator  `', '`

```
    {
        id: 36463570,
        name: 'long laces, red'
    },
    {
        id: 'MD-27927237',
        name: 'Blue T-shirt'
    }
```

and that's why the integration didn't work for multiple products.

It is currently solved, 100% functional and tested :)

**Comment by seldimi** [comment]
Will be added in the next release, later today.
