### ISSUE TITLE
Tags in lowercase letters / You must use uppercase letters for XML tags

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#17]
Good day,

I am studying the xml feed implementation documentation in detail:

and the documentation says:

https://www.glami.sk/info/feed/

Tags in lowercase letters
You must use uppercase letters for XML tags.

![Screenshot 2023-10-07 at 00-48-50 Glami sk - Milujeme módu](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/65feef70-7125-4f09-9534-4e3a53409f64)

but a module glami-feed-generator-pixel-for-woocommerce generate xml feed with lowercase....

example:

```
<shop>
<shopitem>
<item_id>857</item_id>
<itemgroup_id>856</itemgroup_id>
<productname>product name 8</productname>
```

according to the documentation, the lowercase tags are incorrect

**Comment by lukasprelovsky** [comment]
EN documentation:

Tag with small letters
https://www.glami.eco/info/feed/

![Screenshot 2023-10-07 at 16-23-43 Glami eco - We love sustainable fashion](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/aa5a1599-4db3-45cf-857e-212a8b42325c)

**Comment by seldimi** [comment]
Will be fixed in the next release, later today.
