### ISSUE TITLE
Is it possible to use filters to edit XML?

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#18]
Hi

I like the ability to edit my feed using filters.

I saw it on your website, but it looks like the plugin is different

Does this module also support filters? It is not mentioned anywhere.

![Screenshot 2023-10-07 at 14-45-23 WooCommerce Glami XML Feed   Pixel](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/4140df63-f603-44c2-8b5c-8976900edec7)

I could adjust the manufacturer or gender with this filter.

Thank you for your response

**Comment by seldimi** [comment]
You are looking a total different plugin

Hooks will be added in next release, later today.
