### ISSUE TITLE
(xml denied) Please remove size from name - variable products

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#19]
Hi,

they rejected my xml feed because the product name contains sizes.

Do not add sizes in the product name.
https://www.glami.eco/info/feed/#_feed-tag-title

product_attributes

![Screenshot 2023-10-09 at 13-09-34 Vlastnosti ‹ KKTKY - Jediná spodná bielizeň ktorú potrebujete — WordPress](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/e893ea13-2c1d-4d37-bb7e-24b47acac019)

is there a way to disable adding sizes to the product name?

thanks

**Comment by lukasprelovsky** [comment]
WooCommerce have standard use size and colors in product attributes...

**from official woo docu:**

![Screenshot 2023-10-10 at 21-19-55 Variable Product - WooCommerce](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/assets/15073394/e71c0aaf-ebc4-499a-ad56-c5281aef0fd6)

I partially solved the problem with adding sizes to the name by adding on line 85 in the file class-glami-feed-generator-pixel-for-woocommerce-engine.php

**original code:**	```$shopitem->appendChild($domtree->createElement('productname',apply_filters('glami_feed_generator_pixel_custom_product_name', $product->get_name(),$product)));```

**my code:**

```
	$shopitem->appendChild($domtree->createElement('productname',apply_filters('glami_feed_generator_pixel_custom_product_name', $p_parent->get_name(),$product)));
		} else  {
		$shopitem->appendChild($domtree->createElement('productname',apply_filters('glami_feed_generator_pixel_custom_product_name', $product->get_name(),$product)));
```

with this edit I made my product size attribute not added to the product name because it is disabled by glami....

I will be happy if we reach a reasonable solution to the situation...

**Comment by seldimi** [comment]
Hello
You can use the custom hook glami_feed_generator_pixel_custom_product_name we have on title field and change it to whatever you want (eg. custom field)

**Comment by lukasprelovsky** [comment]
Good day,

this update is unmanaged.

GLAMI has a clearly defined and prohibited addition, that sizes (variable product names or the size after the product name) cannot be.

They do not approve the products.

We return to the previous version.

**Comment by lukasprelovsky** [comment]
OK this is solution for my problem

`add_filter( 'glami_feed_generator_pixel_custom_product_name', 'glami_feed_generator_pixel_custom_product_without_attributes' );
function glami_feed_generator_pixel_custom_product_without_attributes( $name ){
	global $product;
	$npweb = $name;
		if ($product->is_type('variable')) {
			$npweb = $product->get_name();
		}
    return $npweb;
}`

this code remove sizes from title.

size is not accept in glami xml feed

https://www.glami.eco/info/feed/#_feed-tag-title  - Do not add sizes in the product name.
