### ISSUE TITLE
How generate XML feed for products

### ISSUE THREAD

**Issue by HakanOsman11** [glami/glami-feed-generator-pixel-for-woocommerce#20]
Hello,

We add a plugin but we can't see from where we can generate a XML feed for the GLAMI. 

Can you help?

Regards,
H.Osman 
CEO OF WEBTRIXIA

**Comment by lukasprelovsky** [comment]
Hi,

it is not well explained in the module description.

You can access feed generation on this subpage:

You must go to the url link

`/wp-admin/admin.php?page=wc-settings&tab=integration&section=glami-feed-generator-pixel-for-woocommerce`

I would recommend the author to improve it this way:
https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/issues/12

**Comment by seldimi** [comment]
Will be added in the next release, later today.
