### ISSUE TITLE
Editing the product name custom only for Glami feed in edit product

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#21]
Hi,

It would be convenient if you could define your own product name that will be displayed in the XML feed

example of the problem we have:

now in XML feed:
**original:**
Product name

**after editing it would be:**
Men's boxers Product name

Other XML generation modules have the option to customize the product name, both directly when editing the product and for variants.

The name would be rewritten that way

It links to this problem
https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/issues/19

**Comment by seldimi** [comment]
Hello
You can use the custom hook glami_feed_generator_pixel_custom_product_name we have on title field and change it to whatever you want (eg. custom field)
