### ISSUE TITLE
Editing the xml file

### ISSUE THREAD

**Issue by SmXxX** [glami/glami-feed-generator-pixel-for-woocommerce#23]
I choosed colour, but in XML file colours are not displaying, also I want to edit the categories as the example in the website, because now in the website from which I am exporting products are not same as in GLAMI and the example says that they should be the same because otherwise the product can go in some other cateogry.

Best Regards!

**Comment by seldimi** [comment]
As per color fit, it will be added in the next release, later today.

As per the other issue, there is a category hook, which you can use.
