### ISSUE TITLE
Variabile products - SIZE (names) IS NOT ACCEPT in XML FEED for GLAMI !

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#25]
Good day,

this update is unmanaged.

GLAMI has a clearly defined and prohibited addition, that sizes (variable product names or the size after the product name) cannot be.

They do not approve the products.

We return to the previous version.

_Originally posted by @lukasprelovsky in https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/issues/19#issuecomment-1932271015_

**Comment by seldimi** [comment]
Please do not open new issues if you don't have to report anything new.
According to WooCommerce, we echo the product title by $product->get_name()

You can use hook glami_feed_generator_pixel_custom_product_name for adding or removing anything you want from the title. There is nothing more we should do.

**Comment by lukasprelovsky** [comment]
OK this is solution for my problem


` add_filter( 'glami_feed_generator_pixel_custom_product_name', 'glami_feed_generator_pixel_custom_product_without_attributes' );
function glami_feed_generator_pixel_custom_product_without_attributes( $name ){
	global $product;
	$npweb = $name;
		if ($product->is_type('variable')) {
			$npweb = $product->get_name();
		}
    return $npweb;
} `

this code remove sizes from title.

size is not accept in glami xml feed

https://www.glami.eco/info/feed/#_feed-tag-title  - Do not add sizes in the product name.
