### ISSUE TITLE
GLAMI TOP - missing api key for insert data field

### ISSUE THREAD

**Issue by lukasprelovsky** [glami/glami-feed-generator-pixel-for-woocommerce#26]
Hi

in settings missing data insert field for API KEY glami top....

merchant_id is different from glami pixel, beware!

we can't update to the new version, it's wrong.

GLAMI TOP has its own api key
GLAMI PIXEL also...

_Originally posted by @seldimi in https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/issues/16#issuecomment-1926397625_

**Comment by seldimi** [comment]
According to https://www.glami.eco/info/reviews/implementation/, the suggested key on merchant_id is the same on glami pixel you can see on pixel overview dashboard.

**Comment by lukasprelovsky** [comment]
I have a different api key for PIXEL and another for GLAMI TOP in the administration

**Comment by seldimi** [comment]
Can you check if is the same but capitalized? As we can only check .gr version of GLAMI

**Comment by lukasprelovsky** [comment]
Glami PIXEL: bf4b89*****************5cbc0
GLami TOP API key: 11f8d2*****************5b48a 

i censored last numbs....

both keys have 32 characters, but they are different.

**Comment by seldimi** [comment]
I will address the issue to GLAMI dev team and will get back to you asap

**Comment by seldimi** [comment]
After talking to GLAMI team, I'm instructed to remove GLAMI TOP integration.

Glami Top is not available in all markets so not all our clients can use it and also there are going to be significant changes in the near future.

Any inquiries you can talk directly to technicalsupport@stileo.it
