### ISSUE TITLE
E_ERROR line  68

### ISSUE THREAD

**Issue by xgpalex28** [glami/glami-feed-generator-pixel-for-woocommerce#3]
Hello,

I've downloaded the zip file and installed the plugin via the Woocommerce Admin. (Upload plugin).

Wordpress Specific Extras:
    wordpress version = 6.0.1
    woocommerce version = 6.7.0
    php version = 7.4.28

E_ERROR pe linia 68 a fișierului /home/REDACTED/www/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Vcs/Api.php. Mesaj eroare: Uncaught Error: Class 'PucReadmeParser' not found in /home/REDACTED/www/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Vcs/Api.php:68
Stack trace:
#0 /home/REDACTED/www/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Vcs/PluginUpdateChecker.php(163): Puc_v4p11_Vcs_Api->getRemoteReadme()
#1 /home/REDACTED/www/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Vcs/PluginUpdateChecker.php(91): Puc_v4p11_Vcs_PluginUpdateChecker->setInfoFromRemoteReadme()
#2 /home/REDACTED/www/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Plugin/UpdateChecker.php(152): Puc_v4p11_Vcs_PluginUpdateChecker->requestInfo()
#3 /home/REDACTED/www/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/UpdateChecker.php(268): Puc_v4p11_Plugin_UpdateChecker->requestUpdate()
#4 /home/REDACTED/www/wp-content/plugins/glami-feed-generator-pixe

Is there a planned fix for this?

**Comment by seldimi** [comment]
Hello
Can you try our new version which was just released?

**Comment by xgpalex28** [comment]
Hello,

Thank you for your reply and work put into this.
It seems to work fine now.
However, I can't seem to find any setting for the module. 
Does it have a page in the admin? Where does it generate the feed? 
Thanks!

**Comment by xgpalex28** [comment]
Found it.
For anyone interested, its here: wp-admin/admin.php?page=wc-settings&tab=integration&section=glami-feed-generator-pixel-for-woocommerce

**Comment by seldimi** [comment]
Yes, we've included it in Integrations tab in WooCommerce.
If you face any further issues, let us know

**Comment by xgpalex28** [comment]
Thank you again.
Have a great day!
