### ISSUE TITLE
MUST FIX

### ISSUE THREAD

**Issue by ruben3219** [glami/glami-feed-generator-pixel-for-woocommerce#4]
Fatal error: Uncaught Error: Class 'PucReadmeParser' not found
in public_html/wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Vcs/Api.php on line 68

Call stack:

    Puc_v4p11_Vcs_Api::getRemoteReadme()
    wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Vcs/PluginUpdateChecker.php:163
    Puc_v4p11_Vcs_PluginUpdateChecker::setInfoFromRemoteReadme()
    wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Vcs/PluginUpdateChecker.php:91
    Puc_v4p11_Vcs_PluginUpdateChecker::requestInfo()
    wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Plugin/UpdateChecker.php:152
    Puc_v4p11_Plugin_UpdateChecker::requestUpdate()
    wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/UpdateChecker.php:268
    Puc_v4p11_UpdateChecker::checkForUpdates()
    wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Plugin/Ui.php:157
    Puc_v4p11_Plugin_Ui::handleManualCheck()
    wp-content/plugins/glami-feed-generator-pixel-for-woocommerce-main/includes/update/Puc/v4p11/Plugin/Ui.php:22
    Puc_v4p11_Plugin_Ui::onAdminInit()
    wp-includes/class-wp-hook.php:307
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:331
    WP_Hook::do_action()
    wp-includes/plugin.php:476
    do_action()
    wp-admin/admin.php:175
    require_once()
    wp-admin/plugins.php:10

**Comment by seldimi** [comment]
Hello
Can you download our newest version and let us know?
