### ISSUE TITLE
URL not resolved

### ISSUE THREAD

**Issue by BGERI95** [glami/glami-feed-generator-pixel-for-woocommerce#6]
I get `net::ERR_NAME_NOT_RESOLVED` for almost every event (except PageView), because the Glami URL cannot be resolved. (see console entry as attached image).
The problem is that the URL in the GET request does not end with glami**.com**. So the domain's TLD is replaced with my own Pixel Key. Probably, it is typo somewhere in the plugin's code, but I cannot find, where it is. 

Can you please look into this and suggest a solution or push a fix in the next update?
(I am using Hungarian engine.)

![image](https://user-images.githubusercontent.com/27287344/201621127-754664af-ed50-4c48-9909-7fa904441989.png)

**Comment by seldimi** [comment]
Hello.
You have to pickup engine from Settings page, so it will get the correct URL

**Comment by BGERI95** [comment]
I picked the Hunagrian engine, but the TLD is filled with my Pixel Key. You can see the URL on the attached picture: `https://www.glami.5228b32...`.

It ends with `5228b32...`, which is my Pixel Key. Instead of `5228b32...` there should be `.hu/`, which corresponds to my Glami engine.

**Comment by seldimi** [comment]
Can you provide any page that code is visible via view source?
On a local test, I can see glam.hu without any keys on query string

**Comment by BGERI95** [comment]
You can open this page: https://kygodesignshop.com/ 
Then scroll down a bit until the products section (it is refered as "Legújabb termékeink"), click on the Add to cart icon on any product, after the new page opens, you will see the error in the browser console.

**Comment by seldimi** [comment]
I am currently getting a 403 - forbidden

**Comment by BGERI95** [comment]
Can I ask, where you are geographically located currently?
You could try to use a Hunagrian VPN to test. https://hide.me/en/free-vpn would be a free alternative.

**Comment by seldimi** [comment]
I'm sorry I cannot support a website which such ways.

**Comment by BGERI95** [comment]
Sorry for the inconvenience. I attached the screenshots that you requested.
![image (1)](https://user-images.githubusercontent.com/27287344/201671396-a9545ae5-9d0e-4b81-9d72-c64da4facb4d.png)
![image](https://user-images.githubusercontent.com/27287344/201671410-8506f6a6-3933-40c5-a750-2d1315c75524.png)

**Comment by ondrejcech** [comment]
Hi, from what I can see, there's a mismatched `countryCode` with `API KEY`.

```
glami(
    'create',
    'IDE_HELYEZD_EL_API_KÓDODAT',
    'hu',
    {
        consent: 1, // The user's consent to the storage analytical cookies on their devices. [0 = no; 1 = yes]
    }
);
```

**Comment by BGERI95** [comment]
Thank you @ondrejcech, this exactly corresponds to my problem inspected in the console. 
Could you suggest a solution to this? FYI: The hungarian API doc can be found here: https://www.glami.hu/info/pixel-telepites/

**Comment by BGERI95** [comment]
As a hotfix on my website, I replaced [Line 43](https://github.com/glami/glami-feed-generator-pixel-for-woocommerce/blob/7e4ad93a66e39315bd4b9c355f3b50b23131e7d9/public/class-glami-feed-generator-pixel-for-woocommerce-public.php#L43) in the /public/class-glami-feed-generator-pixel-for-woocommerce-public.php file as follows:

Original:
`glami('create', '".$this->glami_settings['glami_pixel_key']."', '".$parse."');`
Edited:
`glami('create', '".$this->glami_settings['glami_pixel_key']."', 'hu');`
(hu corresponds to my Glami Hungarian engine.)

@seldimi please fix this issue with localization in the next release. Thank you!

**Comment by seldimi** [comment]
Hello.
We have released an update, can you check and let us know ?
