### ISSUE TITLE
ITEM_ID not matched with feed

### ISSUE THREAD

**Issue by BGERI95** [glami/glami-feed-generator-pixel-for-woocommerce#7]
I am experiencing an issue with ITEM_ID matching with feed and conversion events. 

All three events were implemented, AddtoCart completely correctly. However, the Glami system cannot match the item IDs sent from the ViewContent and Purchase events with the item IDs found in the feed (the ratio of matched item ids is 0%).

Glami support suggested: Please check that you are sending the same item IDs from these events as those found in the feed.
Is there a chance that these two events are implemented incorrectly in the Hungarian engine?

![Screenshot 2022-11-15 at 11 45 08](https://user-images.githubusercontent.com/27287344/201942053-66944792-b223-49ac-9058-6c20802d4512.png)

**Comment by seldimi** [comment]
Could you provide a working URL with a product so you can check the IDs

**Comment by BGERI95** [comment]
You can find the product feed here: https://kygodesignshop.com/wp-content/uploads/glami-feed-generator/glami.xml
_(In case you cannot open it, I attached a more detailed description below.)_

It seems for me so, that the problem only occours for **Variable products** in case of ViewContent and Purchase events. The problem is that in this case the `itemgroup_id` field is used for conversion tracking and not the `item_id`.

I exported a list of unmatched `item_id`-s from Glami:
(See first addtocart instance: 81129 is received as `item_id ` for this event)
![image](https://user-images.githubusercontent.com/27287344/201996231-307d2eb9-1324-45a7-9605-5aa273bfacdf.png)

While this is just an `itemgroup_id` in the XML feed.
![image](https://user-images.githubusercontent.com/27287344/201995134-de1b9f2a-a71c-4263-90cc-b76bd8ded214.png)

**Comment by seldimi** [comment]
If you need support, you will have to allow access to your website without firewall restrictions.

**Comment by BGERI95** [comment]
I look into this restriction problem, could you please provide me (a part) of your IP address so I can check what caused that you are locked out?

**Comment by seldimi** [comment]
Starts from 193.. (its public/static/Greek)

**Comment by BGERI95** [comment]
Thank you for your patience. We disabled all location related restrictions. Please check again and let me know if you are still experiencing issues.

**Comment by seldimi** [comment]
Still getting 403 at your XML

**Comment by BGERI95** [comment]
I exported the current XML document for you as a file: https://drive.google.com/file/d/19Ecg4TQmi8tR8Vvmrm-12jFUMwsmwwMH/view?usp=share_link

**Comment by seldimi** [comment]
I also need to check your website for the printed "javascript" result

**Comment by BGERI95** [comment]
We released all possible restrictrions now, please try again.

**Comment by BGERI95** [comment]
@seldimi do you have any updates regarding this issue?

**Comment by seldimi** [comment]
We have released an update which addresses the issue. You may upgrade and check.
