### ISSUE TITLE
Out of stock products are not excluded from the feed.

### ISSUE THREAD

**Issue by xgpalex28** [glami/glami-feed-generator-pixel-for-woocommerce#8]
Hello,

Is it me or out of stock products are not excluded from the feed? 
I use "Manage stock" and enter quantities for all my products. 
Products (single or variable) with quantity 0 seem to also be in the feed. 

Since Glami is CPC based, can an option to exclude out of stock products be implemented?

Thanks

**Comment by seldimi** [comment]
Please update version 1.0.8
