### ISSUE TITLE
OLD_PRICE parameter

### ISSUE THREAD

**Issue by computel** [glami/glami-feed-generator-pixel-for-woocommerce#9]
Hello is it possible to select which WC price to be sent in feed. Now plugin takes Sale Price for param Price. Is it possible to select Regular price?
Thank you in advanced.

**Comment by seldimi** [comment]
Hello
Feed gets the price from $product->get_price(), which is either the sale price (if product is on sale), or the regular price.
As far as we know, you cannot send a different price to GLAMI than the one you sell on your store.

**Comment by jorobogdanov** [comment]
Hi,

I have also a question about the old_price parameter in the feed. We want to show that our products are on sale so we need to send the old price of the product as well as the regular price. How can we do that or if it's not possible in the moment are you planning some update of the plugin?

**Comment by seldimi** [comment]
Hello
Unfortunately, I cannot answer it as you can see here
https://www.glami.eco/info/feed/#_feed-tag-price

There is only one price feed
